; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_music=music_data_music
.endif

music_data_music:
	.byte 2
	.word @instruments
	.word @samples-4
; 00 : Title
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Magma Plant
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word @song1ch5
	.word @song1ch6
	.word @song1ch7
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_music
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env9,@env10,@env14,@env0 ; 00 : Drums 1
	.word @env22,@env10,@env14,@env0 ; 01 : Drums 2
	.word @env17,@env10,@env14,@env0 ; 02 : Noise_Symbal
	.word @env16,@env10,@env1,@env0 ; 03 : Guitar Solo
	.word @env21,@env10,@env4,@env0 ; 04 : Instrument 1 clone
	.word @env2,@env10,@env14,@env0 ; 05 : Synth
	.word @env3,@env10,@env6,@env0 ; 06 : Wobbly
	.word @env3,@env10,@env14,@env0 ; 07 : VRC6 Bass
	.word @env24,@env23,@env14,@env18 ; 08 : Lead 1
	.word @env12,@env10,@env14,@env0 ; 09 : Vol 4
	.word @env13,@env23,@env15,@env11 ; 0a : Flute 2
	.word @env7,@env23,@env4,@env0 ; 0b : Instrument 1 (2)
	.word @env8,@env10,@env14,@env0 ; 0c : Soft louder

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c1,$c2,$00,$01
@env2:
	.byte $00,$c9,$c8,$c7,$c6,$00,$04
@env3:
	.byte $00,$c8,$c8,$c6,$c6,$c5,$c5,$c4,$04,$c3,$05,$c2,$04,$c1,$00,$0d
@env4:
	.byte $c7,$c5,$00,$01
@env5:
	.byte $00,$cf,$7f,$00,$02
@env6:
	.byte $c2,$c2,$c3,$c3,$c4,$c4,$c3,$c3,$00,$00
@env7:
	.byte $13,$cf,$cf,$ce,$cd,$cb,$ca,$02,$c9,$02,$c8,$02,$c7,$02,$c6,$c6,$c6,$00,$10,$c4,$00,$13
@env8:
	.byte $0b,$ca,$cb,$cc,$cd,$03,$cc,$cc,$cb,$00,$08,$cb,$02,$ca,$02,$c9,$02,$c8,$02,$c7,$02,$c6,$02,$c5,$02,$c4,$02,$c3,$02,$c2,$02,$c1,$00,$1f
@env9:
	.byte $08,$cf,$c6,$c2,$c1,$c0,$00,$05,$c1,$00,$08
@env10:
	.byte $c0,$7f,$00,$01
@env11:
	.byte $00,$c0,$07,$c0,$c0,$c1,$c1,$c0,$c0,$bf,$bf,$00,$03
@env12:
	.byte $00,$c4,$7f,$00,$02
@env13:
	.byte $09,$cf,$cf,$ce,$ce,$cd,$cd,$00,$06,$cc,$cb,$c9,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$c0,$00,$13
@env14:
	.byte $7f,$00,$00
@env15:
	.byte $c2,$7f,$00,$00
@env16:
	.byte $08,$cf,$ce,$cd,$cd,$cc,$00,$05,$c4,$00,$08
@env17:
	.byte $00,$ca,$c8,$c8,$c6,$03,$c4,$07,$c2,$0f,$c1,$08,$c0,$00,$0c
@env18:
	.byte $00,$c0,$1f,$c0,$c1,$c2,$c2,$c1,$c0,$bf,$be,$be,$bf,$c0,$00,$03
@env19:
	.byte $00,$c0,$be,$bc,$bc,$bd,$bf,$c1,$c3,$c4,$c4,$c2,$00,$01
@env20:
	.byte $00,$c0,$bf,$be,$bd,$bd,$be,$bf,$c1,$c2,$c3,$c3,$c2,$c1,$00,$01
@env21:
	.byte $00,$cc,$ca,$c9,$c9,$c8,$c8,$c7,$02,$c6,$03,$c5,$04,$c4,$00,$0d
@env22:
	.byte $00,$cb,$cb,$ca,$ca,$c9,$c8,$c7,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$02,$c1,$02,$c0,$00,$13
@env23:
	.byte $cc,$c0,$00,$01
@env24:
	.byte $09,$c8,$ca,$cb,$cc,$cd,$ce,$00,$06,$cd,$cc,$ca,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$13

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$0f,$40 ; 00 kick15.dmc (Pitch:15)
	.byte $05+.lobyte(FAMISTUDIO_DPCM_PTR),$24,$0f,$40 ; 01 kicksnare.dmc (Pitch:15)
	.byte $0f+.lobyte(FAMISTUDIO_DPCM_PTR),$1c,$0f,$40 ; 02 snare15.dmc (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $73
@song0ref6:
	.byte $4e, $ff, $99, $94
@song0ref10:
	.byte $21, $b3, $23, $b3, $24, $c5, $2d, $a1, $2f, $8f, $2c, $8f, $00, $87, $48, $87, $2d, $b3, $49, .lobyte(@env20), .hibyte(@env20)
	.byte $c5, $49, .lobyte(@env0), .hibyte(@env0), $4a, $81, $00, $8f, $94, $28, $8f, $29, $a1, $2d, $8f, $28, $a1, $29, $8f
	.byte $43, $50, $16, $35, $2d, $45, $85, $48, $87, $00, $8f, $21, $b3, $23, $b3, $24, $c5, $2d, $a1, $2c, $a1, $2f, $87, $48
	.byte $99, $30, $c5, $2f, $c5, $29, $a1, $28, $a1, $24, $a1, $23, $87, $48, $4e, $ff, $99
	.byte $41, $36
	.word @song0ref10
	.byte $2d, $a1, $49, .lobyte(@env19), .hibyte(@env19), $c7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $45, $87, $48
	.byte $41, $40
	.word @song0ref6
	.byte $41, $36
	.word @song0ref10
	.byte $2d, $a1, $49, .lobyte(@env19), .hibyte(@env19), $c7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $45, $87
@song0ref125:
	.byte $48, $7f, $8a, $15, $8f, $15, $8f, $15, $8f, $15, $8f, $15, $8f, $15, $8f, $15, $8f, $15, $8f, $15, $8f, $15, $8f, $15
	.byte $8f, $15, $8f, $15, $8f, $15, $8f, $15, $8f, $15, $8f, $48, $18, $8f, $18, $8f, $18, $8f, $18, $8f, $18, $8f, $18, $8f
	.byte $18, $8f, $18, $8f, $18, $8f, $18, $8f, $18, $8f, $18, $8f, $18, $8f, $18, $8f, $18, $8f, $18, $8f, $48, $79, $86, $1c
	.byte $c5, $1a, $b3, $20, $8f, $21, $a1, $23, $a1, $20, $a1, $21, $a1, $48, $21, $c5, $23, $c5, $21, $a1, $20, $a1, $21, $c5
	.byte $41, $58
	.word @song0ref125
	.byte $48, $7f
@song0ref226:
	.byte $4e, $00, $21, $b3, $23, $b3, $24, $c5, $2d, $a1, $2f, $8f, $2c, $8f, $00, $8f, $2d, $8f, $48, $a3, $49, .lobyte(@env20)
	.byte .hibyte(@env20), $c5, $49, .lobyte(@env0), .hibyte(@env0), $4a, $81, $00, $8f, $86, $28, $8f, $29, $a1, $2d, $8f, $28
	.byte $a1, $29, $8f, $43, $50, $16, $35, $2d, $45, $8d, $00, $8f, $48, $21, $b3, $23, $b3, $24, $c5, $2d, $a1, $2c, $a1, $2f
	.byte $a1, $48, $30, $c5, $32, $c5, $2d, $c5, $2c, $c5, $48
	.byte $41, $32
	.word @song0ref226
	.byte $2f, $c5, $2d, $a1, $49, .lobyte(@env19), .hibyte(@env19), $c7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $45, $a1
	.byte $48, $7d, $86
@song0ref320:
	.byte $2d, $c5, $49, .lobyte(@env19), .hibyte(@env19), $a3, $45, $a1, $49, .lobyte(@env0), .hibyte(@env0), $4a, $86, $2b
	.byte $c5, $49, .lobyte(@env19), .hibyte(@env19), $a3, $45, $a1, $48, $76, $49, .lobyte(@env0), .hibyte(@env0), $4a, $86
	.byte $1c, $b3, $1f, $b3, $21, $a1, $1c, $b3, $1a, $b3, $1c, $a1, $48, $7d
	.byte $41, $12
	.word @song0ref320
	.byte $1f, $b3, $21, $a1, $48, $7d
	.byte $41, $16
	.word @song0ref320
	.byte $48, $7d, $2d, $c5, $49, .lobyte(@env19), .hibyte(@env19), $a3, $45, $a1, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $86, $2b, $c5, $49, .lobyte(@env19), .hibyte(@env19), $a3, $45, $a1, $48, $76, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $86, $1c, $b3, $20, $b3, $20, $a1, $1c, $b3, $20, $b3, $1c, $a1, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref420:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
	.byte $7b, $86
@song0ref446:
	.byte $28, $b3, $26, $b3, $28, $c5, $30, $a1, $32, $8f, $2f, $8f, $00, $8f, $30, $8f, $a3, $49, .lobyte(@env20), .hibyte(@env20)
	.byte $c5, $49, .lobyte(@env0), .hibyte(@env0), $4a, $81, $00, $8f, $86, $24, $8f, $26, $a1, $26, $8f, $23, $a1, $23, $8f
	.byte $00, $a1, $24, $b3, $26, $b3, $28, $c5, $29, $a1, $28, $a1, $2c, $a1, $2d, $c5, $2c, $c5, $2d, $a1, $2c, $a1, $2d, $a1
	.byte $26, $a1
	.byte $41, $32
	.word @song0ref446
	.byte $85, $00, $87, $21, $87, $00, $85, $28, $85, $00, $87, $24, $87, $00, $85, $2d, $a1, $43, $50, $02, $39, $37, $45, $9f
	.byte $7f, $8a, $10
@song0ref541:
	.byte $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f
@song0ref556:
	.byte $10, $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f, $13, $8f, $13, $8f, $13, $8f, $13, $8f
	.byte $13, $8f, $13, $8f, $13, $8f, $13, $8f, $13, $8f, $13, $8f, $13, $8f, $13, $8f, $13, $8f, $13, $8f, $13, $8f, $13, $8f
	.byte $10, $8f, $15, $8f, $18, $8f, $15, $8f, $0e, $8f, $14, $8f, $17, $8f, $14, $8f, $1c, $8f, $15, $8f, $1a, $8f, $17, $8f
	.byte $1c, $8f, $14, $8f, $17, $8f, $15, $8f, $18, $8f, $11, $8f, $11, $8f, $11, $8f, $17, $8f, $10, $8f, $10, $8f, $10, $8f
	.byte $15
	.byte $41, $1f
	.word @song0ref541
	.byte $41, $61
	.word @song0ref556
	.byte $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f, $00, $ff, $ff, $9d
	.byte $41, $15
	.word @song0ref420
	.byte $7b, $86
@song0ref683:
	.byte $24, $e9, $45, $a1, $26, $e9, $45, $a1, $24, $ff, $8d, $45, $c5, $00, $c5, $24, $e9, $45, $a1, $26, $e9, $45, $a1, $28
	.byte $ff, $8d, $45, $c5, $00, $c5
	.byte $41, $1e
	.word @song0ref683
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $41, $18
	.word @song0ref420
	.byte $41, $18
	.word @song0ref420
	.byte $41, $18
	.word @song0ref420
	.byte $41, $18
	.word @song0ref420
	.byte $41, $18
	.word @song0ref420
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $78
@song0ref740:
	.byte $80, $21, $8f, $21, $8f, $82, $1f, $8f
@song0ref748:
	.byte $80, $21, $8f, $21, $8f, $21, $8f, $82, $1f, $8f, $80, $21, $8f, $21, $8f, $21, $8f, $82, $1f, $8f, $80, $21, $8f, $21
	.byte $8f, $21, $8f, $82, $1f, $8f, $80, $21, $85, $82, $1f, $87
	.byte $41, $22
	.word @song0ref740
	.byte $41, $22
	.word @song0ref740
@song0ref790:
	.byte $80, $21, $8f, $21, $8f, $82, $1f, $8f, $80, $21, $8f, $21, $8f, $21, $8f, $82, $1f, $8f, $80, $21, $8f, $82, $1f, $8f
	.byte $80, $21, $8f, $82, $1f, $8f, $80, $21, $8f, $82, $1f, $8f, $80, $21, $8f, $82, $1f, $8f, $1f, $87, $1f, $85, $1f, $b3
	.byte $41, $1c
	.word @song0ref748
	.byte $41, $22
	.word @song0ref740
	.byte $41, $22
	.word @song0ref740
	.byte $41, $24
	.word @song0ref790
	.byte $41, $1c
	.word @song0ref748
	.byte $41, $22
	.word @song0ref740
	.byte $41, $22
	.word @song0ref740
	.byte $41, $24
	.word @song0ref790
	.byte $41, $1c
	.word @song0ref748
	.byte $41, $22
	.word @song0ref740
	.byte $41, $22
	.word @song0ref740
	.byte $41, $22
	.word @song0ref790
@song0ref874:
	.byte $80
@song0ref875:
	.byte $20, $85, $00, $87, $20, $87, $20, $85, $82, $1f, $8f, $80, $20, $87, $20, $85, $20, $85, $00, $87, $20, $87, $20, $85
	.byte $82, $1f, $8f, $80, $20, $87, $20, $85
	.byte $41, $1c
	.word @song0ref875
	.byte $41, $1c
	.word @song0ref875
	.byte $41, $1c
	.word @song0ref875
	.byte $41, $1c
	.word @song0ref875
	.byte $41, $1c
	.word @song0ref875
	.byte $41, $1c
	.word @song0ref875
@song0ref925:
	.byte $20, $85, $00, $87, $20, $87, $20, $85, $82, $1f, $8f, $80, $20, $87, $20, $85, $82, $1f, $8f, $1f, $8f, $1e, $8f, $1e
	.byte $8f
	.byte $41, $1c
	.word @song0ref874
	.byte $41, $1c
	.word @song0ref875
	.byte $41, $1c
	.word @song0ref875
	.byte $41, $1c
	.word @song0ref875
	.byte $41, $1c
	.word @song0ref875
	.byte $41, $1c
	.word @song0ref875
	.byte $41, $1c
	.word @song0ref875
	.byte $41, $16
	.word @song0ref925
	.byte $41, $22
	.word @song0ref740
	.byte $41, $22
	.word @song0ref740
	.byte $41, $22
	.word @song0ref740
	.byte $41, $24
	.word @song0ref790
	.byte $41, $1c
	.word @song0ref748
	.byte $41, $22
	.word @song0ref740
	.byte $41, $22
	.word @song0ref740
	.byte $41, $22
	.word @song0ref790
	.byte $84
@song0ref999:
	.byte $21, $8f, $80, $21, $8f, $84, $20, $8f
@song0ref1007:
	.byte $80, $21, $8f, $84, $21, $8f, $80, $21, $8f, $84, $20, $8f, $80, $21, $8f, $84, $21, $8f, $80, $21, $8f, $84, $20, $8f
	.byte $80, $21, $8f, $84, $21, $8f, $80, $21, $8f, $84, $20, $8f, $20, $8f
	.byte $41, $1e
	.word @song0ref999
	.byte $41, $18
	.word @song0ref1007
	.byte $80, $21, $8f, $84, $21, $8f, $80, $21, $8f, $84, $20, $8f, $20, $8f
	.byte $41, $1e
	.word @song0ref999
	.byte $41, $18
	.word @song0ref1007
	.byte $80, $21, $8f, $84, $21, $8f, $80, $21, $8f, $84, $20, $8f, $20, $8f
	.byte $41, $1e
	.word @song0ref999
	.byte $41, $18
	.word @song0ref1007
	.byte $80, $21, $8f, $84, $21, $8f, $80, $21, $8f, $84, $20, $8f, $20, $8f
	.byte $41, $1e
	.word @song0ref999
	.byte $80, $21, $8f, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref1115:
	.byte $01, $8f, $00, $8f, $03, $8f, $00
@song0ref1122:
	.byte $a1, $01, $8f, $03, $8f, $00, $8f, $01, $8f, $00, $8f, $03, $8f, $00, $a1, $01, $8f, $03, $8f, $00, $8f
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $15
	.word @song0ref1115
	.byte $8f, $02, $8f, $01, $85, $01, $87, $02, $8f, $01, $85, $01, $87
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $15
	.word @song0ref1115
	.byte $8f, $02, $8f, $01, $85, $01, $87, $02, $8f, $01, $85, $01, $87
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $15
	.word @song0ref1115
	.byte $8f, $02, $8f, $01, $85, $01, $87, $02, $8f, $01, $85, $01, $87
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $15
	.word @song0ref1115
@song0ref1227:
	.byte $8f, $02, $8f, $01, $85, $01, $87, $02, $8f, $01, $85, $01, $87
@song0ref1240:
	.byte $01, $8f, $00, $8f, $03, $8f, $00, $8f, $01, $87, $01, $85, $01, $8f, $03, $8f, $01, $8f, $00, $8f, $01, $8f, $03, $8f
	.byte $00, $8f, $01, $8f, $01, $87, $01, $85, $03, $8f, $01, $8f
	.byte $41, $22
	.word @song0ref1240
	.byte $02, $8f
	.byte $41, $24
	.word @song0ref1240
	.byte $41, $22
	.word @song0ref1240
	.byte $02, $8f
	.byte $41, $24
	.word @song0ref1240
	.byte $41, $22
	.word @song0ref1240
	.byte $02, $8f
	.byte $41, $24
	.word @song0ref1240
	.byte $41, $22
	.word @song0ref1240
	.byte $02, $8f
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $15
	.word @song0ref1115
	.byte $41, $14
	.word @song0ref1227
	.byte $41, $15
	.word @song0ref1122
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $15
	.word @song0ref1115
	.byte $41, $14
	.word @song0ref1227
	.byte $41, $15
	.word @song0ref1122
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $15
	.word @song0ref1115
	.byte $8f, $03, $85, $03, $87, $01, $8f, $03, $8f, $01, $8f
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $1c
	.word @song0ref1115
	.byte $41, $15
	.word @song0ref1115
	.byte $8f, $03, $85, $03, $87, $01, $8f, $03, $8f, $01, $8f, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $7f
@song0ref1386:
	.byte $4e, $00, $96
@song0ref1389:
	.byte $21, $b3, $23, $b3, $24, $c5, $2d, $a1, $2f, $8f, $2c, $8f, $00, $8f, $2d, $8f, $a3, $49, .lobyte(@env20), .hibyte(@env20)
	.byte $c5, $49, .lobyte(@env0), .hibyte(@env0), $4a, $81, $00, $8f, $96, $28, $8f, $29, $a1, $2d, $8f, $28, $a1, $29, $8f
	.byte $43, $50, $16, $35, $2d, $45, $8d, $00, $8f, $21, $b3, $23, $b3, $24, $c5, $2d, $a1, $2c, $a1, $2f, $a1, $30, $c5, $2f
	.byte $c5, $29, $a1, $28, $a1, $24, $a1, $23, $a1, $4e, $00
	.byte $41, $34
	.word @song0ref1389
	.byte $2d, $a1, $49, .lobyte(@env19), .hibyte(@env19), $c7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $45, $a1
	.byte $41, $3c
	.word @song0ref1386
	.byte $4e, $00
	.byte $41, $34
	.word @song0ref1389
	.byte $2d, $a1, $49, .lobyte(@env19), .hibyte(@env19), $c7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $45, $a1, $00, $a1
	.byte $96
@song0ref1501:
	.byte $2d, $a1, $2c, $a1, $2f, $a1, $2d, $a1, $00, $e9, $00, $a1, $2d, $a1, $2c, $a1, $2f, $a1, $2d, $a1, $00, $e9, $a3, $30
	.byte $a1, $2f, $a1, $2c, $a1, $2d, $a1, $2c, $a1, $29, $a1, $26, $a1, $28, $b3, $2b, $8f, $2c, $b3, $2d, $8f, $30, $a1, $2f
	.byte $a1, $2d, $a1, $43, $50, $01, $39, $38, $a1, $00, $a1
	.byte $41, $35
	.word @song0ref1501
	.byte $76, $4e, $ff, $4f, $06, $00, $97, $98
@song0ref1571:
	.byte $21, $b3, $23, $b3, $24, $c5, $2d, $a1, $2f, $8f, $2c, $8f, $00, $87, $87, $2d, $b3, $49, .lobyte(@env20), .hibyte(@env20)
	.byte $c5, $49, .lobyte(@env0), .hibyte(@env0), $4a, $81, $00, $8f, $98, $28, $8f, $29, $a1, $2d, $8f, $28, $a1, $29, $8f
	.byte $43, $50, $16, $35, $2d, $45, $85, $87, $00, $8f, $21, $b3, $23, $b3, $24, $c5, $2d, $a1, $2c, $a1, $2f, $87, $99, $30
	.byte $c5, $32, $c5, $2d, $c5, $2c, $ab, $4e, $ff, $4f, $06, $99
	.byte $41, $34
	.word @song0ref1571
	.byte $2f, $c5, $2d, $a1, $49, .lobyte(@env19), .hibyte(@env19), $c7, $45, $85, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $81, $99, $00, $ff, $ff, $83, $7f, $4e, $00, $88, $2d, $c5, $49, .lobyte(@env19), .hibyte(@env19), $c7, $45, $c3, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $81, $00, $c5, $ff, $ff, $9f, $4e, $00, $88
@song0ref1694:
	.byte $2d, $c5, $49, .lobyte(@env19), .hibyte(@env19), $c7, $45, $c3, $49, .lobyte(@env0), .hibyte(@env0), $4a, $81, $00
	.byte $c5, $88, $1c, $b3, $1f, $b3, $21, $a1, $1f, $b3, $21, $b3, $23, $a1, $4e, $00
	.byte $41, $14
	.word @song0ref1694
	.byte $4e, $00, $2c, $c5, $49, .lobyte(@env19), .hibyte(@env19), $c7, $45, $c3, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $81, $00, $c5, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $88
@song0ref1749:
	.byte $1c, $b3, $1a, $b3, $1c, $c5, $18, $a1, $1a, $8f, $1c, $8f, $00, $8f, $50, $f7, $27, $28, $87, $43, $1c, $85, $eb, $00
	.byte $8f, $4e, $ff, $1c, $8f, $1d, $a1, $21, $8f, $1c, $a1, $1d, $a1, $4e, $00, $00, $8f, $18, $b3, $18, $b3, $18, $c5, $23
	.byte $a1, $24, $a1, $20, $a1, $21, $c5, $20, $c5, $21, $a1, $24, $a1, $21, $a1, $20, $a1
	.byte $41, $35
	.word @song0ref1749
	.byte $28, $a1, $24, $a1
	.byte $41, $39
	.word @song0ref1749
	.byte $41, $35
	.word @song0ref1749
	.byte $28, $a1, $24, $a1
@song0ref1831:
	.byte $00, $bd, $73, $2d, $a1, $2c, $a1, $2f, $a1, $00, $85, $7f, $21, $a1, $20, $a1, $23, $a1, $21, $a1, $00, $99, $73, $2d
	.byte $a1, $2c, $a1, $2f, $a9, $7f, $21, $a1, $20, $a1, $23, $a1, $21, $c5, $20, $c5, $24, $a1, $26, $a1, $23, $a1, $1c, $a1
	.byte $1d, $b3, $1d, $8f, $20, $c5, $2d, $a1, $2c, $a1, $30, $c5
	.byte $41, $38
	.word @song0ref1831
	.byte $8c
@song0ref1895:
	.byte $40, $09, $8f, $40, $09
@song0ref1900:
	.byte $8f, $40, $09, $8f
@song0ref1904:
	.byte $40, $09, $8f, $40, $09, $8f
@song0ref1910:
	.byte $09, $8f, $40, $09, $8f, $40, $09
@song0ref1917:
	.byte $8f
@song0ref1918:
	.byte $40, $09, $8f, $40, $09, $8f, $40, $09, $8f, $40, $09, $8f, $40, $09, $8f, $09, $8f, $40, $09, $8f, $40, $09
@song0ref1940:
	.byte $8f, $40, $0c, $8f, $40, $0c, $8f, $40, $0c, $8f, $40, $0c, $8f, $40, $0c, $8f, $0c, $8f, $40, $0c, $8f, $40, $0c, $8f
	.byte $02, $8f, $02, $8f, $02, $8f, $02, $8f, $02, $8f, $0e, $8f, $02, $8f, $02
	.byte $41, $11
	.word @song0ref1917
	.byte $41, $18
	.word @song0ref1918
@song0ref1985:
	.byte $02, $8f, $02, $8f, $02, $8f, $02, $8f, $40, $0c, $8f, $40, $0c, $8f, $40, $0c, $8f, $40, $0c, $8f, $40, $0b, $8f, $40
	.byte $0b, $8f, $40, $0b, $8f, $40, $0b
	.byte $41, $11
	.word @song0ref1917
	.byte $41, $2f
	.word @song0ref1918
	.byte $41, $11
	.word @song0ref1917
	.byte $41, $18
	.word @song0ref1918
@song0ref2028:
	.byte $02, $8f, $02, $8f, $02, $8f, $02, $8f, $40, $09, $8f, $40, $09, $8f, $40, $09, $8f, $40, $09, $8f, $40, $09, $8f, $40
	.byte $09, $8f, $40, $09, $8f, $40, $09, $8f, $88
@song0ref2061:
	.byte $15, $b3, $17, $b3, $18, $a1, $17, $b3, $18, $b3, $20, $a1, $21, $e7, $45, $a3, $1f, $e9, $45, $a1, $15, $b3, $17, $b3
	.byte $18, $a1, $17, $b3, $18, $b3, $20, $a1, $21, $b3, $23, $b3, $24, $a1, $21, $b3, $23, $b3, $24, $a1
	.byte $41, $20
	.word @song0ref2061
	.byte $20, $b3, $23, $b3, $24, $a1, $20, $b3, $23, $b3, $20, $a1, $42
	.word @song0ch6loop
@song0ch7:
@song0ch7loop:
	.byte $55, $01, $8e
	.byte $41, $3f
	.word @song0ref1895
	.byte $41, $11
	.word @song0ref1940
@song0ref2133:
	.byte $40, $0b, $8f, $40, $0b, $8f, $40, $0b, $8f, $40, $0b, $8f, $40, $0b, $8f, $0b, $8f, $40, $0b, $8f, $0b, $8f, $40, $0c
	.byte $8f, $40, $0c, $8f, $40, $0c, $8f, $40, $0c, $8f
	.byte $41, $17
	.word @song0ref1985
	.byte $41, $11
	.word @song0ref1917
	.byte $41, $2f
	.word @song0ref1918
	.byte $41, $11
	.word @song0ref1940
	.byte $41, $18
	.word @song0ref2133
	.byte $41, $18
	.word @song0ref2028
	.byte $41, $3f
	.word @song0ref1895
	.byte $41, $11
	.word @song0ref1940
	.byte $41, $18
	.word @song0ref2133
	.byte $41, $17
	.word @song0ref1985
	.byte $41, $11
	.word @song0ref1917
	.byte $41, $2f
	.word @song0ref1918
	.byte $41, $11
	.word @song0ref1940
	.byte $41, $18
	.word @song0ref2133
	.byte $41, $18
	.word @song0ref2028
	.byte $41, $1e
	.word @song0ref1895
	.byte $09
	.byte $41, $11
	.word @song0ref1940
@song0ref2219:
	.byte $40, $0c, $8f, $40, $0c, $8f, $40, $0c, $8f, $40, $0c, $8f, $40, $0c, $8f, $0c, $8f, $40, $0c, $8f, $0c, $8f, $04, $8f
	.byte $04, $8f, $04, $8f, $10, $8f, $08, $8f, $08, $8f, $08, $8f, $14, $8f, $09, $8f, $15, $8f, $0b, $8f, $17, $8f, $08, $8f
	.byte $14, $8f, $09, $8f, $15, $8f, $0c, $8f, $0c, $8f, $0c, $8f, $18, $8f, $0b, $8f, $0b, $8f, $0b, $8f, $17, $8f, $09, $8f
	.byte $09, $8f, $09, $8f, $15
	.byte $41, $13
	.word @song0ref1900
	.byte $41, $14
	.word @song0ref1910
	.byte $09
	.byte $41, $11
	.word @song0ref1940
	.byte $41, $47
	.word @song0ref2219
	.byte $41, $13
	.word @song0ref1900
	.byte $41, $35
	.word @song0ref1910
	.byte $41, $11
	.word @song0ref1917
	.byte $41, $18
	.word @song0ref1918
	.byte $41, $17
	.word @song0ref1985
	.byte $41, $11
	.word @song0ref1917
	.byte $41, $2f
	.word @song0ref1918
	.byte $41, $11
	.word @song0ref1917
	.byte $41, $18
	.word @song0ref1918
	.byte $41, $18
	.word @song0ref2028
@song0ref2339:
	.byte $05, $8f, $05, $8f, $05, $8f, $05, $8f, $05, $8f, $05, $8f, $11, $8f, $05
@song0ref2354:
	.byte $8f, $40, $07, $8f, $40, $07, $8f, $40, $07, $8f, $40, $07, $8f, $40, $07, $8f, $40, $07, $8f, $07, $8f, $40, $07, $8f
	.byte $40, $09, $8f, $40, $09, $8f, $40, $09, $8f, $40, $09, $8f, $40, $09, $8f, $09, $8f, $40, $09, $8f, $09
	.byte $41, $11
	.word @song0ref2354
	.byte $41, $2a
	.word @song0ref2339
	.byte $41, $16
	.word @song0ref1904
	.byte $41, $2f
	.word @song0ref2339
	.byte $41, $11
	.word @song0ref2354
	.byte $41, $20
	.word @song0ref2339
	.byte $40, $08, $8f, $40, $08, $8f, $40, $08, $8f, $40, $08, $8f, $40, $08, $8f, $40, $08, $8f, $40, $08, $8f, $08, $8f, $40
	.byte $08, $8f, $40, $08, $8f, $40, $08, $8f, $40, $08, $8f, $40, $08, $8f, $40, $08, $8f, $08, $8f, $40, $08, $8f, $42
	.word @song0ch7loop
@song1ch0:
	.byte $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $00, $ff, $bd, $48, $ff, $bf, $48, $ff, $8f, $78, $4f, $01
	.byte $90, $21, $ad, $48, $24, $dd, $26, $dd, $48, $28, $ff, $8d, $29, $ad, $48, $28, $c5, $26, $c5, $28, $ad, $48, $24, $ff
	.byte $bd, $48, $26, $dd, $23, $dd
@song1ref70:
	.byte $48, $00, $ff, $bd, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $8f, $7f, $92, $50, $ff, $37, $38, $ad, $48, $4f, $00, $82
@song1ref94:
	.byte $2d, $83, $15, $83, $7b, $4f, $01, $43, $2d, $83, $18, $83, $7e, $4f, $02, $43, $2d, $83, $1c, $83, $7a, $4f, $00, $43
	.byte $2d, $83, $21, $83, $7d, $4f, $01, $43, $2d, $83, $15, $83, $79
@song1ref131:
	.byte $4f, $02, $43, $2d, $83, $18, $83, $7c, $4f, $00, $43, $2d, $83, $1c, $83, $77, $4f, $01, $43, $2d, $83, $21, $83, $7b
	.byte $4f, $02, $43, $2d, $83, $15, $83, $76, $4f, $00, $43, $2d, $83, $18, $83, $7a, $4f, $01, $43, $2d, $83, $1c, $83, $75
	.byte $4f, $02, $43, $2d, $83, $21, $83, $79, $4f, $00, $43, $2d, $83, $15, $83, $74, $4f, $01, $43, $2d, $83, $18, $83, $78
	.byte $4f, $02, $43, $2d, $83, $15, $83, $73, $4f, $01, $43, $2d, $83, $18, $83, $48, $77, $4f, $00, $2d, $83, $15, $83, $75
	.byte $4f, $01, $43, $2d, $83, $18, $83, $79, $4f, $02, $43, $2d, $83, $1c, $83, $76, $4f, $00, $43, $2d, $83, $21, $83, $7b
	.byte $4f, $01, $43, $2d, $83, $15, $83, $77
	.byte $41, $40
	.word @song1ref131
	.byte $77
	.byte $41, $2c
	.word @song1ref131
@song1ref266:
	.byte $48, $77, $4f, $00, $2f, $83, $14, $83, $75, $4f, $01, $43, $2f, $83, $17, $83, $79, $4f, $02, $43, $2f, $83, $1c, $83
	.byte $76, $4f, $00, $43, $2f, $83, $20, $83, $7b, $4f, $01, $43, $2f, $83, $14, $83, $77, $4f, $02, $43, $2f, $83, $17, $83
	.byte $7c, $4f, $00, $43, $2f, $83, $1c, $83, $77, $4f, $01, $43, $2f, $83, $20, $83, $7b, $4f, $02, $43, $2e, $83, $13, $83
	.byte $76, $4f, $00, $43, $2b, $83, $16, $83, $7a, $4f, $01, $43, $2e, $83, $1b, $83, $75, $4f, $02, $43, $2b, $83, $1f, $83
	.byte $79, $4f, $00, $43, $2e, $83, $13, $83, $74, $4f, $01, $43, $2b, $83, $16, $83, $78, $4f, $02, $43, $2e, $83, $13, $83
	.byte $73, $4f, $01, $43, $2b, $83, $16, $83
	.byte $41, $5f
	.word @song1ref70
	.byte $77
	.byte $41, $40
	.word @song1ref131
	.byte $77
	.byte $41, $2c
	.word @song1ref131
	.byte $41, $40
	.word @song1ref266
	.byte $48, $7f, $4f, $00
	.byte $41, $54
	.word @song1ref94
	.byte $77
	.byte $41, $40
	.word @song1ref131
	.byte $77
	.byte $41, $2c
	.word @song1ref131
	.byte $41, $40
	.word @song1ref266
@song1ref426:
	.byte $48, $77, $4f, $00, $29, $83, $11, $83, $75, $4f, $01, $43, $29, $83, $15, $83, $79, $4f, $02, $43, $29, $83, $18, $83
	.byte $76, $4f, $00, $43, $29, $83, $1d, $83, $7b, $4f, $01, $43, $29, $83, $11, $83, $77, $4f, $02, $43, $29, $83, $15, $83
	.byte $7c, $4f, $00, $43, $29, $83, $18, $83, $77, $4f, $01, $43, $29, $83, $1d, $83, $7b, $4f, $02, $43, $29, $83, $11, $83
	.byte $76, $4f, $00, $43, $29, $83, $15, $83, $7a, $4f, $01, $43, $29, $83, $18, $83, $75, $4f, $02, $43, $29, $83, $1d, $83
	.byte $79, $4f, $00, $43, $29, $83, $11, $83, $74, $4f, $01, $43, $29, $83, $15, $83, $78, $4f, $02, $43, $29, $83, $11, $83
	.byte $73, $4f, $01, $43, $29, $83, $15, $83
	.byte $41, $40
	.word @song1ref426
	.byte $41, $40
	.word @song1ref426
	.byte $41, $20
	.word @song1ref426
	.byte $7b, $4f, $02, $43, $28, $83, $10, $83, $76, $4f, $00, $43, $28, $83, $14, $83, $7a, $4f, $01, $43, $28, $83, $17, $83
	.byte $75, $4f, $02, $43, $28, $83, $1c, $83, $79, $4f, $00, $43, $28, $83, $10, $83, $74, $4f, $01, $43, $28, $83, $14, $83
	.byte $78, $4f, $02, $43, $28, $83, $10, $83, $73, $4f, $01, $43, $28, $83, $14, $83, $42
	.word @song1ch0loop
@song1ch1:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
@song1ch1loop:
	.byte $00, $ff, $bd, $79, $90, $10, $dd, $13, $dd, $15, $ff, $bd, $15, $dd, $17, $dd, $18, $ff, $8d, $1a, $ad, $18, $c5, $13
	.byte $c5, $15, $ad, $15, $ff, $bd, $1d, $dd, $1c, $dd, $7a, $51, $fd, $20, $1c, $89, $43, $50, $7f, $28, $10, $89, $1c, $89
	.byte $43, $50, $7f, $28, $10, $89, $1c, $89, $43, $50, $7f, $28, $10, $89, $1c, $89, $43, $50, $7f, $28, $10, $87, $81, $7f
	.byte $00, $dd
@song1ref721:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $df, $79, $23, $dd, $24, $dd, $26, $dd
	.byte $29, $dd, $28, $dd, $42
	.word @song1ch1loop
@song1ch2:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
@song1ch2loop:
	.byte $41, $28
	.word @song1ref721
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $42
	.word @song1ch2loop
@song1ch3:
@song1ref823:
	.byte $78
@song1ref824:
	.byte $80
@song1ref825:
	.byte $24, $89, $23, $89, $22, $89, $22, $89, $82, $1f, $89, $80, $23, $89, $22, $89, $22, $89, $24, $89, $23, $89, $22, $89
	.byte $22, $89, $82, $1f, $89, $80, $23, $89, $22, $89, $22, $89
	.byte $41, $1e
	.word @song1ref825
	.byte $82, $1f, $89
	.byte $41, $20
	.word @song1ref824
@song1ref870:
	.byte $24
@song1ref871:
	.byte $89, $23, $89, $22, $89, $22, $89, $82, $1f, $89, $80, $23, $89, $22, $89, $22, $89, $24, $89, $82, $1f, $89, $80, $22
	.byte $89, $22, $89, $82, $1f, $89, $80, $23, $89, $82, $1f, $89, $1f, $89
	.byte $41, $20
	.word @song1ref824
	.byte $41, $1e
	.word @song1ref825
	.byte $82, $1f, $89
	.byte $41, $20
	.word @song1ref824
	.byte $41, $20
	.word @song1ref870
@song1ch3loop:
	.byte $41, $20
	.word @song1ref823
	.byte $41, $1e
	.word @song1ref825
	.byte $82, $1f, $89
	.byte $41, $20
	.word @song1ref824
	.byte $41, $20
	.word @song1ref870
	.byte $41, $20
	.word @song1ref824
	.byte $41, $1e
	.word @song1ref825
	.byte $82, $1f, $89
	.byte $41, $20
	.word @song1ref824
	.byte $41, $20
	.word @song1ref870
@song1ref955:
	.byte $80
@song1ref956:
	.byte $23, $89, $23, $89, $22, $89, $22, $89, $82, $1f, $89, $80, $23, $89, $22, $89, $22, $89, $23, $89, $23, $89, $22, $89
	.byte $22, $89, $82, $1f, $89, $80, $23, $89, $22, $89, $22, $89
	.byte $41, $1e
	.word @song1ref956
	.byte $82, $1f, $89
	.byte $41, $20
	.word @song1ref955
	.byte $23
	.byte $41, $1f
	.word @song1ref871
	.byte $41, $20
	.word @song1ref824
	.byte $41, $1e
	.word @song1ref825
	.byte $82, $1f, $89
	.byte $41, $20
	.word @song1ref824
	.byte $41, $20
	.word @song1ref870
	.byte $41, $20
	.word @song1ref824
	.byte $41, $1e
	.word @song1ref825
	.byte $82, $1f, $89
	.byte $41, $20
	.word @song1ref824
	.byte $41, $20
	.word @song1ref870
	.byte $41, $20
	.word @song1ref824
	.byte $41, $1e
	.word @song1ref825
	.byte $82, $1f, $89
	.byte $41, $20
	.word @song1ref824
	.byte $41, $20
	.word @song1ref870
	.byte $41, $20
	.word @song1ref824
	.byte $41, $1e
	.word @song1ref825
	.byte $82, $1f, $89
	.byte $41, $20
	.word @song1ref824
	.byte $41, $20
	.word @song1ref870
	.byte $41, $20
	.word @song1ref824
	.byte $41, $1e
	.word @song1ref825
	.byte $82, $1f, $89
	.byte $41, $20
	.word @song1ref824
	.byte $41, $20
	.word @song1ref870
	.byte $42
	.word @song1ch3loop
@song1ch4:
@song1ref1083:
	.byte $01, $89, $00, $a1, $03, $89, $00, $a1, $01, $89, $00, $a1, $03, $89, $00, $a1, $01, $89, $00, $a1, $03, $89, $00, $a1
	.byte $01, $89, $00, $a1, $03, $89, $00, $95, $03, $89, $01, $89, $00, $a1, $03, $89, $00, $a1, $01, $89, $00, $a1, $03, $89
	.byte $00, $a1, $01, $89, $00, $a1, $03, $89, $00, $a1, $01, $89, $03, $89, $00, $95, $03, $89, $00, $89, $03, $89, $03, $89
	.byte $41, $48
	.word @song1ref1083
@song1ch4loop:
	.byte $41, $48
	.word @song1ref1083
	.byte $41, $48
	.word @song1ref1083
	.byte $00, $ff, $bd, $ff, $bf, $ff, $bf, $df, $01, $89, $03, $89, $00, $95, $03, $89, $00, $89, $02, $89, $02, $89
	.byte $41, $48
	.word @song1ref1083
	.byte $41, $48
	.word @song1ref1083
	.byte $41, $48
	.word @song1ref1083
	.byte $41, $48
	.word @song1ref1083
	.byte $41, $48
	.word @song1ref1083
	.byte $42
	.word @song1ch4loop
@song1ch5:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
@song1ch5loop:
	.byte $7f, $88, $10, $ff, $bd, $15, $dd, $17, $dd, $18, $ff, $bd, $1c, $dd, $1f, $dd, $21, $ff, $8d, $23, $ad, $21, $c5, $23
	.byte $c5, $24, $ad, $28, $ff, $bd, $21, $dd, $20, $dd, $7e, $21, $89, $43, $50, $7f, $2d, $15, $89, $7c, $43, $21, $89, $43
	.byte $50, $7f, $2d, $15, $89, $79, $43, $21, $89, $43, $50, $7f, $2d, $15, $89, $74, $43, $21, $89, $43, $50, $7f, $2d, $15
	.byte $89, $00, $dd, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $7f, $15, $dd, $10, $dd, $15, $dd
	.byte $17, $dd, $1c, $ff, $8d, $1b, $ad, $1c, $ad, $20, $ad, $1b, $ad, $1f, $ad, $7b
@song1ref1334:
	.byte $24, $89, $00, $89, $24, $89, $00, $89, $24, $89, $00, $89, $24, $89, $00, $89, $24, $89, $00, $95, $23, $89, $00, $95
	.byte $24, $95, $8b, $00, $89, $24, $89, $00, $89, $24, $89, $00, $89, $24, $89, $00, $89, $24, $89, $00, $95, $26, $89, $00
	.byte $95, $28, $95, $8b, $00, $89, $28, $89, $00, $89, $28, $89, $00, $89, $28, $89, $00, $89, $28, $89, $00, $95, $28, $89
	.byte $00, $95, $28, $95, $43, $27, $ad, $2c, $ad, $22, $ad, $2b, $ad
	.byte $41, $54
	.word @song1ref1334
	.byte $21, $dd, $23, $dd, $24, $dd, $26, $dd, $28, $dd, $29, $dd, $2d, $dd, $2c, $dd, $42
	.word @song1ch5loop
@song1ch6:
	.byte $8c
@song1ref1442:
	.byte $40, $09, $a1, $40, $09, $95, $40, $09, $89, $40, $09, $95, $40, $09, $95, $09, $89, $00, $89, $40, $09, $95, $40, $09
	.byte $95, $40, $09, $a1, $40, $09, $95, $40, $09, $89, $40, $09, $95, $40, $09, $95, $09, $89, $00, $89, $40, $09, $95, $40
	.byte $09, $95, $40, $09, $a1, $40, $09, $95, $40, $09, $89, $40, $09, $95, $40, $09, $95, $09, $89, $00, $89, $40, $09, $95
	.byte $40, $09, $95, $40, $09, $a1, $40, $09, $95, $40, $09, $89, $09, $95, $40, $07, $a1, $40, $07, $95, $40, $07, $89, $07
@song1ref1538:
	.byte $95, $40, $05, $a1, $40, $05, $95, $40, $05, $89, $40, $05, $95, $40, $05, $95, $05, $89, $00, $89, $40, $05, $95, $40
	.byte $05, $95, $40, $05, $a1, $40, $05, $95, $40, $05, $89, $40, $05, $95, $40, $05, $95, $05, $89, $00, $89, $40, $05, $95
	.byte $40, $05, $95, $40, $05, $a1, $40, $05, $95, $40, $05, $89, $40, $05, $95, $40, $05, $95, $05, $89, $00, $89, $40, $05
	.byte $95, $40, $05, $95, $40, $05, $a1, $40, $05, $95, $40, $05, $89, $05, $95, $40, $04, $a1, $40, $04, $95, $40, $04, $89
	.byte $08, $95
@song1ch6loop:
	.byte $41, $8c
	.word @song1ref1442
	.byte $00, $ff, $bd, $ff, $bf, $ff, $bf, $df
@song1ref1648:
	.byte $40, $0a, $a1, $0a, $95, $00, $89, $40, $0a, $95
@song1ref1658:
	.byte $40, $09, $95, $40, $09, $95, $40, $09, $89, $09, $89, $40, $07, $95, $40, $09, $a1, $40, $09, $89, $00, $95, $09, $89
	.byte $09, $89, $40, $09, $95, $40, $09, $95, $40, $09, $89, $09, $89, $40, $07, $95, $40, $09, $a1, $40, $09, $89, $00, $95
	.byte $09, $89, $0b, $89, $0c, $95, $40, $0c, $95, $40, $0c, $89, $0c, $89, $40, $0c, $95, $40, $0c, $a1, $0c, $89, $00, $95
	.byte $40, $0c, $95, $40, $0b, $95, $0b, $95, $0b, $89, $0b, $89, $40, $0b, $95
	.byte $41, $4c
	.word @song1ref1648
	.byte $41, $4c
	.word @song1ref1648
	.byte $41, $4c
	.word @song1ref1648
	.byte $40, $0a, $a1, $0a, $95, $00, $89, $40, $0a
	.byte $41, $47
	.word @song1ref1538
	.byte $42
	.word @song1ch6loop
@song1ch7:
	.byte $55, $01, $8e
	.byte $41, $8c
	.word @song1ref1442
@song1ch7loop:
	.byte $41, $8c
	.word @song1ref1442
	.byte $41, $44
	.word @song1ref1658
	.byte $41, $4c
	.word @song1ref1648
	.byte $41, $4c
	.word @song1ref1648
	.byte $41, $4c
	.word @song1ref1648
	.byte $41, $4c
	.word @song1ref1648
	.byte $40, $0a, $a1, $0a, $95, $00, $89, $40, $0a
	.byte $41, $47
	.word @song1ref1538
	.byte $42
	.word @song1ch7loop
